IF NOT EXISTS (SELECT 1 FROM UNITTYPE WHERE UNITTYPEID=0)
BEGIN
	INSERT INTO UNITTYPE
	VALUES
	(0,'UNKNOWN')
END

IF NOT EXISTS (SELECT 1 FROM UNITTYPE WHERE UNITTYPEID=1)
BEGIN
	INSERT INTO UNITTYPE
	VALUES
	(1,'WASHER')
END

IF NOT EXISTS (SELECT 1 FROM UNITTYPE WHERE UNITTYPEID=2)
BEGIN
	INSERT INTO UNITTYPE
	VALUES
	(2,'DRYER')
END
